services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - "5433:5432"
    networks:
      - pg-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-network
  
networks:
  pg-network:

volumes:
  pg-data: